FROM alpine:3.18

# Instala Tor y herramientas necesarias
RUN apk add --no-cache tor bash

# Copiamos el archivo de configuración del torrc
COPY torrc /etc/tor/torrc

# Exponemos los puertos necesarios
EXPOSE 9050 9051

# Comando de arranque
CMD ["tor", "-f", "/etc/tor/torrc"]
